package com.scsinfinity.udhd.services.audit.internalaudit.dto;

public enum IARevenueNCapitalReceiptsEnum {
	//@formatter:off
PROPERTY_TAX,
OTHER_TAX,
FEES_AND_FINES,
USER_CHARGES,
OTHER_NON_TAX_REVENUE,
INCOME_FROM_INTEREST,
OTHER_REVENUE_INCOME,
STATE_ASSIGNED_REVENUE,
STATE_FC_GRANTS,
OCTRAI_COMPENSATION,
OTHER_STATE_GOVT_TRANSFERS,
CFC_GRANTS,
OTHER_CENTRAL_GOVT_TRANSFERS,
OTHERS,
SALES_OF_MUNICIPAL_LAND,
LOANS,
STATE_CAPITAL_ACCOUNT_GRANTS,
CENTRAL_CAPITAL_ACCOUNT_GRANTS,
OTHER_CAPITAL_RECEIPTS
//@formatter:on
}
