package com.scsinfinity.udhd.services.audit.internalaudit.dto;

public enum PartByTypeAuditObsEnum {
//@formatter:off
	NON_MAINTENANCE_OF_BOOKS,
	IRREGULARITIES_IN_PROCUREMENT,
	NON_COMPLIANCE_OF_DIRECTIVES,
	NON_COMPLIANCE_OF_ACT_N_RULES,
	LACK_OF_INTERNAL_CONTROL_MEASURES,
	DEFICIENCY_IN_PAYROLL_SYSTEM,
	PHYSICAL_VERIFICATION_OF_INVENTORY,
	ADVANCES_N_THEIR_ADJUSTMENT,
	ANY_OTHER_MATTER_IN_DUE_COURSE
}
